### PR TITLE
ci: add a 32 bit container

### PR DESCRIPTION
**Pull request by williamcroberts**
Add a 32 bit container to help ensure there are no 32 bit bugs.

Signed-off-by: William Roberts <william.c.roberts@intel.com>

### CODE REVIEW

**Comment by williamcroberts** [comment]
Ahh yeah these need more setup....

**Comment by AndreasFuchsSIT** [comment]
@williamcroberts The fails seem to be related to some seccomp stuff ?

**Comment by williamcroberts** [comment]
Looks like we need `--seccomp action=none`

**Comment by williamcroberts** [comment]
@AndreasFuchsSIT review please?

**Review by AndreasFuchsSIT — APPROVED** [review]

**Pull request merged**
