### PR TITLE
Enhanced init_tpm_parent(). It could use RSA algorithm to create primary key.

### PR DESCRIPTION
**Pull request by coolfengyu**
It could use RSA algorithm to create primary key.
Some old TPM 2.0 devices don't support ECC, such as Infineon SLB9665TT2.0 TPM version 2.0.
This init_tpm_parent() will check the TPM device whether support ECC. If it supports, it uses ECC. Otherwise, it will use RSA.

### CODE REVIEW

**Comment by PeterHuewe** [comment]
One minor correction to your commit message.
There is no _version 2.0_ of SLB 9665 TPM2.0. The FW Version without ECC is 5.00
`TPM_PT_FIRMWARE_VERSION_1: 0x00050000`
Newer versions of course have ECC - but there might be other TPMs from other vendors who also don't support ECC, so the commit itself makes sense.

**Comment by coolfengyu** [comment]
Is there any update for this review?

**Comment by AndreasFuchsSIT** [comment]
Please change the commit message according to PeterHuewe's comment.
Then I will merge.

**Comment by coolfengyu** [comment]
OK, the commit message has been updated.

**Pull request merged**
