### PR TITLE
GitHub actions

### PR DESCRIPTION
**Pull request by williamcroberts**
- Update failwrite.sh to not rely on DAC permissions and instead rely on ENOENT for negative testing.
- Add Github Actions and run in multiple container flavors and compilers.
- Add a whitespace checker that runs on PRs.
- Remove Travis yaml file.

@AndreasFuchsSIT I still need to get coverity working. I'd like to take this and file a bug to add a feature to add automagic coverity scanning if that's okay?

Fixes: #197

### CODE REVIEW

**Comment by williamcroberts** [comment]
FYI you can see build history in actions from my fork:
- Docker builds: https://github.com/williamcroberts/tpm2-tss-engine/actions?query=workflow%3A%22Testing+in+Docker+Containers%22

- Whitespace checker: https://github.com/williamcroberts/tpm2-tss-engine/actions?query=workflow%3A%22Whitespace+Checker%22

**Review by AndreasFuchsSIT — APPROVED** [review]
LGTM
Please feel free to add coverity

**Comment by williamcroberts** [comment]
Im gonna pull this now, and then work on a separate PR for coverity.

**Comment by williamcroberts** [comment]
@AndreasFuchsSIT I also updated your branch protection rules to require DCO and the various "actions" to pass. I saw that you had travis passing as a requirement.

**Pull request merged**
