### PR TITLE
tpm2tss_tpm2data_readtpm(): be smarter about guessing emptyAuth.

### PR DESCRIPTION
**Pull request by asac**
With this patch tpm2tss_tpm2data_readtpm will assume empty Auth not only
if it has explicitely tested it for NODA objects, but also if it finds
an empty authPolicy in public areas.

With this change using tpm2_create'ed objects with default attributes
grows convenience as it does not ask for password if no auth policy is set.

Signed-off-by: Alexander Sack <asac@pantacor.com>

### CODE REVIEW

**Comment by AndreasFuchsSIT** [comment]
authPolicy and authValue are completely different things. The engine currently makes no use of authPolicy anyways. The authValue is in the private area, not the public area.

Using this patch will increment the da-counter and may lead to lockout...
Sorry...

**Comment by asac** [comment]
@AndreasFuchsSIT you are of course right. sorry for me being confused. In the end i am indeed after PCR policy support for tpm2tss engine; have there been patches, WIP things at some point that we could lean on to get a good start? Otherwise, could you outline the general approach we should take to introduce such support so I can see if we can help getting a first iteration going? Thanks for your input!

**Comment by AndreasFuchsSIT** [comment]
Once FAPI is in place in tpm2-tss, we can leverage FAPI keys from here and have full policy support...
________________________________

**Comment by asac** [comment]
ok cool. Is ETA close for FAPI in tpm2-tss? Do you know @AndreasFuchsSIT ?

**Comment by AndreasFuchsSIT** [comment]
There's an RFC-PR open...
We need to do some more coding, but you can have a look and play around:
https://github.com/tpm2-software/tpm2-tss/pull/1537

________________________________

**Pull request closed without merging**
