### PR TITLE
tpm2-tss-engine: add digest like sha1,sha256

### PR DESCRIPTION
**Pull request by aaronUniontech**
Signed-off-by: zhangya <zhangya@uniontech.com>

### CODE REVIEW

**Comment by AndreasFuchsSIT** [comment]
I'm sorry, but I do not see a reason to have the TPM calculate a digest.
Could you explain to me, why this would be an advantage ?
Because otherwise, I'd have to reject this PR

**Comment by aaronUniontech** [comment]
> I'm sorry, but I do not see a reason to have the TPM calculate a digest. Could you explain to me, why this would be an advantage ? Because otherwise, I'd have to reject this PR

maybe all the work can be done by the hardwork.
yes, it's not such necessary.

**Comment by williamcroberts** [comment]
> > I'm sorry, but I do not see a reason to have the TPM calculate a digest. Could you explain to me, why this would be an advantage ? Because otherwise, I'd have to reject this PR
> 
> maybe all the work can be done by the hardwork. yes, it's not such necessary.

The TPM is very slow, so in general unless you're working in a way where you need a ticket, theirs no point to using the TPM to hash over software.

**Comment by AndreasFuchsSIT** [comment]
So I appreciate the effort of this implementation but I'll have to decline the PR.
I'm sorry, but there is no advantage, only disadvantages in calculating the digest inside the TPM.

**Pull request closed without merging**
